# Generated by extendr: Do not edit by hand
# nolint start
#' @usage NULL
#' @useDynLib FinancialFunctions
NULL

# ── Annuity functions ─────────────────────────────────────────────────────────

#' @export
fv <- function(rate, nper, pmt, pv, pmt_at_beginning) .Call("wrap__fv", rate, nper, pmt, pv, pmt_at_beginning)

#' @export
pv <- function(rate, nper, pmt, fv, pmt_at_beginning) .Call("wrap__pv", rate, nper, pmt, fv, pmt_at_beginning)

#' @export
pmt <- function(rate, nper, pv, fv, pmt_at_beginning) .Call("wrap__pmt", rate, nper, pv, fv, pmt_at_beginning)

#' @export
ipmt <- function(rate, per, nper, pv, fv, pmt_at_beginning) .Call("wrap__ipmt", rate, per, nper, pv, fv, pmt_at_beginning)

#' @export
ppmt <- function(rate, per, nper, pv, fv, pmt_at_beginning) .Call("wrap__ppmt", rate, per, nper, pv, fv, pmt_at_beginning)

#' @export
cumipmt <- function(rate, nper, pv, start_period, end_period, pmt_at_beginning) .Call("wrap__cumipmt", rate, nper, pv, start_period, end_period, pmt_at_beginning)

#' @export
cumprinc <- function(rate, nper, pv, start_period, end_period, pmt_at_beginning) .Call("wrap__cumprinc", rate, nper, pv, start_period, end_period, pmt_at_beginning)

#' @export
nper <- function(rate, pmt, pv, fv, pmt_at_beginning) .Call("wrap__nper", rate, pmt, pv, fv, pmt_at_beginning)

#' @export
rate <- function(nper, pmt, pv, fv, pmt_at_beginning, guess) .Call("wrap__rate", nper, pmt, pv, fv, pmt_at_beginning, guess)

#' @export
ispmt <- function(rate, per, nper, pv) .Call("wrap__ispmt", rate, per, nper, pv)

# ── Cash flow functions ───────────────────────────────────────────────────────

#' @export
npv <- function(rate, values) .Call("wrap__npv", rate, values)

#' @export
irr <- function(values) .Call("wrap__irr", values)

#' @export
mirr <- function(values, finance_rate, reinvest_rate) .Call("wrap__mirr", values, finance_rate, reinvest_rate)

#' @export
xnpv <- function(rate, values, dates) .Call("wrap__xnpv", rate, values, dates)

#' @export
xirr <- function(values, dates) .Call("wrap__xirr", values, dates)

# ── Depreciation functions ────────────────────────────────────────────────────

#' @export
sln <- function(cost, salvage, life) .Call("wrap__sln", cost, salvage, life)

#' @export
syd <- function(cost, salvage, life, per) .Call("wrap__syd", cost, salvage, life, per)

#' @export
db <- function(cost, salvage, life, per, month) .Call("wrap__db", cost, salvage, life, per, month)

#' @export
ddb <- function(cost, salvage, life, per, factor) .Call("wrap__ddb", cost, salvage, life, per, factor)

#' @export
vdb <- function(cost, salvage, life, start_period, end_period, factor, no_switch) .Call("wrap__vdb", cost, salvage, life, start_period, end_period, factor, no_switch)

#' @export
amorlinc <- function(cost, date_purchased, first_period, salvage, period, rate, basis) .Call("wrap__amorlinc", cost, date_purchased, first_period, salvage, period, rate, basis)

#' @export
amordegrc <- function(cost, date_purchased, first_period, salvage, period, rate, basis) .Call("wrap__amordegrc", cost, date_purchased, first_period, salvage, period, rate, basis)

# ── Coupon date functions ─────────────────────────────────────────────────────

#' @export
coupdaybs <- function(settlement, maturity, frequency, basis) .Call("wrap__coupdaybs", settlement, maturity, frequency, basis)

#' @export
coupdays <- function(settlement, maturity, frequency, basis) .Call("wrap__coupdays", settlement, maturity, frequency, basis)

#' @export
coupdaysnc <- function(settlement, maturity, frequency, basis) .Call("wrap__coupdaysnc", settlement, maturity, frequency, basis)

#' @export
coupncd <- function(settlement, maturity, frequency, basis) .Call("wrap__coupncd", settlement, maturity, frequency, basis)

#' @export
couppcd <- function(settlement, maturity, frequency, basis) .Call("wrap__couppcd", settlement, maturity, frequency, basis)

#' @export
coupnum <- function(settlement, maturity, frequency, basis) .Call("wrap__coupnum", settlement, maturity, frequency, basis)

# ── Bond and security functions ───────────────────────────────────────────────

#' @export
price <- function(settlement, maturity, rate, yld, redemption, frequency, basis) .Call("wrap__price", settlement, maturity, rate, yld, redemption, frequency, basis)

#' @export
pricedisc <- function(settlement, maturity, discount, redemption, basis) .Call("wrap__pricedisc", settlement, maturity, discount, redemption, basis)

#' @export
pricemat <- function(settlement, maturity, issue, rate, yld, basis) .Call("wrap__pricemat", settlement, maturity, issue, rate, yld, basis)

#' @export
yield_ <- function(settlement, maturity, rate, pr, redemption, frequency, basis) .Call("wrap__yield_", settlement, maturity, rate, pr, redemption, frequency, basis)

#' @export
yielddisc <- function(settlement, maturity, pr, redemption, basis) .Call("wrap__yielddisc", settlement, maturity, pr, redemption, basis)

#' @export
yieldmat <- function(settlement, maturity, issue, rate, pr, basis) .Call("wrap__yieldmat", settlement, maturity, issue, rate, pr, basis)

#' @export
disc <- function(settlement, maturity, pr, redemption, basis) .Call("wrap__disc", settlement, maturity, pr, redemption, basis)

#' @export
intrate <- function(settlement, maturity, investment, redemption, basis) .Call("wrap__intrate", settlement, maturity, investment, redemption, basis)

#' @export
received <- function(settlement, maturity, investment, discount, basis) .Call("wrap__received", settlement, maturity, investment, discount, basis)

#' @export
duration <- function(settlement, maturity, coupon, yld, frequency, basis) .Call("wrap__duration", settlement, maturity, coupon, yld, frequency, basis)

#' @export
mduration <- function(settlement, maturity, coupon, yld, frequency, basis) .Call("wrap__mduration", settlement, maturity, coupon, yld, frequency, basis)

#' @export
accrint <- function(issue, first_interest, settlement, rate, par, frequency, basis) .Call("wrap__accrint", issue, first_interest, settlement, rate, par, frequency, basis)

#' @export
accrintm <- function(issue, settlement, rate, par, basis) .Call("wrap__accrintm", issue, settlement, rate, par, basis)

#' @export
oddfprice <- function(settlement, maturity, issue, first_coupon, rate, yld, redemption, frequency, basis) .Call("wrap__oddfprice", settlement, maturity, issue, first_coupon, rate, yld, redemption, frequency, basis)

#' @export
oddfyield <- function(settlement, maturity, issue, first_coupon, rate, pr, redemption, frequency, basis) .Call("wrap__oddfyield", settlement, maturity, issue, first_coupon, rate, pr, redemption, frequency, basis)

#' @export
oddlprice <- function(settlement, maturity, last_interest, rate, yld, redemption, frequency, basis) .Call("wrap__oddlprice", settlement, maturity, last_interest, rate, yld, redemption, frequency, basis)

#' @export
oddlyield <- function(settlement, maturity, last_interest, rate, pr, redemption, frequency, basis) .Call("wrap__oddlyield", settlement, maturity, last_interest, rate, pr, redemption, frequency, basis)

# ── Miscellaneous functions ───────────────────────────────────────────────────

#' @export
effect <- function(nominal_rate, npery) .Call("wrap__effect", nominal_rate, npery)

#' @export
nominal <- function(effect_rate, npery) .Call("wrap__nominal", effect_rate, npery)

#' @export
dollarde <- function(fractional_dollar, fraction) .Call("wrap__dollarde", fractional_dollar, fraction)

#' @export
dollarfr <- function(decimal_dollar, fraction) .Call("wrap__dollarfr", decimal_dollar, fraction)

#' @export
fvschedule <- function(principal, schedule) .Call("wrap__fvschedule", principal, schedule)

#' @export
rri <- function(nper, pv, fv) .Call("wrap__rri", nper, pv, fv)

#' @export
pduration <- function(rate, pv, fv) .Call("wrap__pduration", rate, pv, fv)

#' @export
tbillprice <- function(settlement, maturity, discount) .Call("wrap__tbillprice", settlement, maturity, discount)

#' @export
tbillyield <- function(settlement, maturity, pr) .Call("wrap__tbillyield", settlement, maturity, pr)

#' @export
tbilleq <- function(settlement, maturity, discount) .Call("wrap__tbilleq", settlement, maturity, discount)

# nolint end
